In [ ]:
#변수중요도 100 이하 : optt_nbtm_s, urlb_fc_yn, heltp_pf_ntyn, ac_rst_diff,
#smrtg_5y_passed_yn, nur_hosp_yn, mdct_inu_rclss_dcd, ar_rclss_cd, prm_nvcd,
#optt_blcnt_s

#다중공선성 가능성을 보이는 변수 : prm_nvcd/inamt_nvcd,

In [3]:
drop_col = ["optt_nbtm_s", "urlb_fc_yn", "heltp_pf_ntyn", "ac_rst_diff",
"smrtg_5y_passed_yn", "nur_hosp_yn", "mdct_inu_rclss_dcd", "ar_rclss_cd", 
"prm_nvcd", "optt_blcnt_s"]

In [1]:
import pandas as pd

In [2]:
train_df=pd.read_csv("./data/train.csv")
test_df=pd.read_csv("./data/test.csv")

In [7]:
train_df = train_df.drop(drop_col, axis=1)
train_df

,ID,ac_ctr_diff,hsp_avg_optt_bilg_isamt_s,hsp_avg_surop_bilg_isamt_s,fds_cust_yn,hspz_dys_s,inamt_nvcd,hsp_avg_diag_bilg_isamt_s,blrs_cd,dsas_ltwt_gcd,...,hsp_avg_hspz_bilg_isamt_s,mtad_cntr_yn,surop_blcnt_s,dsas_avg_optt_bilg_isamt_s,isrd_age_dcd,hspz_blcnt_s,dsas_avg_surop_bilg_isamt_s,dsas_avg_hspz_bilg_isamt_s,bilg_isamt_s,target
0,0,6,0.1303,0.0000,0,0.3452,4,0.0000,12,1,...,1.6021,0,0.0000,1.2002,3,10.0000,1.1701,1.2612,0.4240,1
1,1,6,0.0000,0.5770,0,0.0000,4,0.0000,2,3,...,0.0000,0,1.0000,0.0000,4,0.0000,0.1508,0.0023,0.8602,0
2,2,6,0.0000,0.2885,1,0.0000,6,0.0000,2,3,...,0.0000,0,1.0000,0.0000,4,0.0000,0.1508,0.0023,0.4301,1
3,3,4,0.0197,0.0680,0,0.8056,6,0.0587,8,3,...,0.5638,0,0.0000,0.0000,9,1.4444,0.0863,0.1920,0.2509,1
4,4,5,0.0000,0.0000,0,0.4167,2,0.0000,8,3,...,0.4464,0,0.0000,0.0000,0,1.3333,0.0863,0.1920,0.0323,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377923,377923,6,0.7997,1.0588,0,0.1454,2,1.2320,11,1,...,0.4626,0,1.0000,1.1610,3,1.3242,1.2955,1.1660,9.5518,2
377924,377924,0,2.3047,1.2993,0,1.7434,99,0.5585,9,1,...,0.7844,0,0.7896,1.2228,7,6.6667,1.1811,1.0199,0.0000,2
377925,377925,0,0.0000,0.0000,0,22.6866,99,0.0000,8,1,...,10.6758,0,0.0000,0.0000,7,0.7234,1.0221,1.5595,0.0000,2
377926,377926,6,1.3784,1.4096,0,0.0832,1,0.8812,10,1,...,0.6908,0,1.0000,1.2499,3,0.6667,1.2766,1.2040,2.7239,2
377927,377927,6,0.0000,0.0000,0,1.2672,3,0.0000,8,3,...,1.4340,0,0.0000,0.4178,3,0.6667,0.1488,0.5451,0.8072,2

In [8]:
test_df = test_df.drop(drop_col, axis=1)
test_df

,ID,ac_ctr_diff,hsp_avg_optt_bilg_isamt_s,hsp_avg_surop_bilg_isamt_s,fds_cust_yn,hspz_dys_s,inamt_nvcd,hsp_avg_diag_bilg_isamt_s,blrs_cd,dsas_ltwt_gcd,...,kcd_gcd,hsp_avg_hspz_bilg_isamt_s,mtad_cntr_yn,surop_blcnt_s,dsas_avg_optt_bilg_isamt_s,isrd_age_dcd,hspz_blcnt_s,dsas_avg_surop_bilg_isamt_s,dsas_avg_hspz_bilg_isamt_s,bilg_isamt_s
0,0,5,0.0000,0.2938,0,0.0000,9,0.0000,2,3,...,4,0.0000,0,1.0548,0.0000,2,0.0000,0.1397,0.1309,0.4242
1,1,6,1.5266,2.1745,0,0.0000,6,1.3936,2,1,...,9,0.7517,0,1.0000,0.5200,2,0.0000,1.0923,0.5344,1.7688
2,2,6,1.6061,1.6884,0,0.0000,3,1.0524,1,1,...,3,1.2090,0,0.0000,1.1593,2,0.0000,1.2975,1.1660,43.0108
3,3,6,0.1228,0.8927,0,0.1847,4,0.3889,10,1,...,3,0.2785,0,1.2660,1.1593,4,0.6667,1.2975,1.1660,4.1867
4,4,6,0.0000,0.2440,0,0.0000,2,0.0000,2,3,...,14,0.0000,0,1.0000,0.0000,2,0.0000,0.1397,0.1309,0.4431
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22067,22067,6,0.0000,0.1975,0,0.0000,6,0.0000,2,3,...,4,0.0267,0,1.0000,0.0000,2,0.0000,0.1397,0.1309,0.3226
22068,22068,6,0.0000,0.5815,0,0.0000,2,0.0000,8,3,...,14,0.9098,0,0.0000,0.0000,2,0.6667,0.1397,0.1309,0.0000
22069,22069,4,0.0000,0.0741,0,0.0000,2,0.0000,2,3,...,8,0.0000,0,2.0000,0.0000,5,0.0000,0.1462,0.0072,0.2165
22070,22070,5,1.7263,1.8482,0,0.0000,4,0.8596,1,1,...,3,1.3442,0,0.6732,0.8690,4,0.0000,0.9450,0.8726,4.6630
22071,22071,6,0.0000,0.3336,0,0.1713,2,0.0000,10,3,...,4,0.2458,0,1.0000,0.0000,3,1.0989,0.1397,0.1309,0.1726

In [11]:
train_df.to_csv("./data/train1.csv", index=False)
test_df.to_csv("./data/test1.csv", index=False)

In [1]:
import pandas as pd

In [2]:
pd.read_csv("./data/sample.csv")

          ID  target
0          0       0
1          1       0
2          2       0
3          3       0
4          4       0
...      ...     ...
22067  22067       0
22068  22068       0
22069  22069       0
22070  22070       0
22071  22071       0

[22072 rows x 2 columns]